// BenCode's app icon, "Ember Bronze": a turned-bronze B whose counters are
// a prompt (› and _) lit like embers from inside, backlit on a dark tile.
// It is drawn here as SVG, so this script is the icon's source:
//
//   NODE_PATH="$(npm root -g)" node packaging/macos/icon.mjs
//
// writes icon.svg (the landing page's too), icon-1024.png (bundle.sh makes
// AppIcon.icns from it) and assets/app-icon.png (the rail's "Updated to"
// card), rendering with Chromium through Playwright.
import { createRequire } from 'node:module';
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const f = (v) => +v.toFixed(1);

// The macOS icon grid: an 824px continuous-corner tile centred on 1024.
function squircle(cx = 512, cy = 512, r = 412, n = 5, steps = 160) {
  const pts = [];
  for (let i = 0; i < steps; i++) {
    const t = (i / steps) * 2 * Math.PI;
    const c = Math.cos(t);
    const s = Math.sin(t);
    pts.push(`${f(cx + r * Math.sign(c) * Math.abs(c) ** (2 / n))} ${f(cy + r * Math.sign(s) * Math.abs(s) ** (2 / n))}`);
  }
  return `M${pts.join('L')}Z`;
}

const hex = (c) => [1, 3, 5].map((i) => parseInt(c.slice(i, i + 2), 16));
function mix(a, b, k) {
  const A = hex(a);
  const B = hex(b);
  return `#${A.map((v, i) => Math.round(v + (B[i] - v) * k).toString(16).padStart(2, '0')).join('')}`;
}
// A colour at `v` (0..1) along `stops`.
function sample(stops, v) {
  const x = Math.min(1, Math.max(0, v));
  for (let i = 1; i < stops.length; i++) {
    if (x <= stops[i][0]) {
      const [o0, c0] = stops[i - 1];
      const [o1, c1] = stops[i];
      return mix(c0, c1, (x - o0) / (o1 - o0 || 1));
    }
  }
  return stops[stops.length - 1][1];
}
// Turned metal: thin wedges round a centre whose brightness rises and falls
// twice a turn (SVG has no conic gradient; a blur hides the seams).
function conic(cx, cy, radius, stops, phase, amp) {
  const steps = 720;
  let out = '';
  for (let i = 0; i < steps; i++) {
    const a0 = (i / steps) * 2 * Math.PI;
    const a1 = ((i + 1.4) / steps) * 2 * Math.PI;
    const a = (a0 + a1) / 2;
    const v = 0.5 + amp[0] * Math.cos(2 * (a - phase)) + amp[1] * Math.cos(4 * (a - phase * 1.7) + 0.6);
    out += `<path d="M${cx} ${cy}L${f(cx + radius * Math.cos(a0))} ${f(cy + radius * Math.sin(a0))}L${f(cx + radius * Math.cos(a1))} ${f(cy + radius * Math.sin(a1))}Z" fill="${sample(stops, v)}"/>`;
  }
  return out;
}

const TILE = squircle();
// The B: a stem, a top bowl and a wider bottom one, rounded outer corners.
const t = 276;
const b = 748;
const m = 500;
const r1 = (m - t) / 2;
const r2 = (b - m) / 2;
const w1 = 160;
const w2 = 176;
const cr = 32;
const width = w2 + r2;
const x0 = Math.round(512 - width / 2) - 4;
const B = `M${x0 + cr} ${t}H${x0 + w1}A${r1} ${r1} 0 0 1 ${x0 + w1} ${m}H${x0 + w2}A${r2} ${r2} 0 0 1 ${x0 + w2} ${b}H${x0 + cr}Q${x0} ${b} ${x0} ${b - cr}V${t + cr}Q${x0} ${t} ${x0 + cr} ${t}Z`;
// The counters: a chevron in the top bowl, a cursor in the bottom one.
const chev = `M${x0 + 88} ${t + 68}L${x0 + 176} ${(t + m) / 2}L${x0 + 88} ${m - 68}`;
const cur = `M${x0 + 96} ${b - 90}H${x0 + 226}`;
const bcx = x0 + width * 0.48;
const bcy = (t + b) / 2;

const EMBER = '#ff4a00';
const EMBER_HOT = '#ff7a1a';
const TILE_STOPS = [[0, '#0c0909'], [0.5, '#1d1715'], [1, '#2c2421']];
const BRONZE = [[0, '#2e231f'], [0.3, '#6a4c3e'], [0.55, '#a77c63'], [0.8, '#dcb79c'], [1, '#f6e4d4']];

const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="1024" viewBox="0 0 1024 1024">
<!-- BenCode app icon, "Ember Bronze". Generated by icon.mjs; edit that. -->
<defs>
  <clipPath id="tile"><path d="${TILE}"/></clipPath>
  <clipPath id="bshape"><path d="${B}"/></clipPath>
  <radialGradient id="halo" cx="${bcx}" cy="${bcy}" r="380" gradientUnits="userSpaceOnUse">
    <stop offset="0" stop-color="${EMBER}" stop-opacity="0.65"/>
    <stop offset="0.45" stop-color="${EMBER}" stop-opacity="0.29"/>
    <stop offset="1" stop-color="${EMBER}" stop-opacity="0"/>
  </radialGradient>
  <radialGradient id="vignette" cx="0.5" cy="0.46" r="0.72">
    <stop offset="0.55" stop-color="#000" stop-opacity="0"/>
    <stop offset="1" stop-color="#000" stop-opacity="0.5"/>
  </radialGradient>
  <linearGradient id="rim" x1="0" y1="0" x2="0" y2="1">
    <stop offset="0" stop-color="#fff" stop-opacity="0.3"/>
    <stop offset="0.25" stop-color="#fff" stop-opacity="0.05"/>
    <stop offset="0.85" stop-color="#fff" stop-opacity="0.02"/>
    <stop offset="1" stop-color="#fff" stop-opacity="0.12"/>
  </linearGradient>
  <linearGradient id="bevel" x1="0" y1="${t}" x2="0" y2="${b}" gradientUnits="userSpaceOnUse">
    <stop offset="0" stop-color="#fff" stop-opacity="0.85"/>
    <stop offset="0.4" stop-color="#fff" stop-opacity="0.08"/>
    <stop offset="1" stop-color="${EMBER}" stop-opacity="0.7"/>
  </linearGradient>
  <linearGradient id="shade" x1="0" y1="${t}" x2="0" y2="${b}" gradientUnits="userSpaceOnUse">
    <stop offset="0" stop-color="#fff" stop-opacity="0.12"/>
    <stop offset="0.5" stop-color="#000" stop-opacity="0"/>
    <stop offset="1" stop-color="#000" stop-opacity="0.28"/>
  </linearGradient>
  <linearGradient id="recess" x1="0" y1="0" x2="0" y2="1">
    <stop offset="0" stop-color="#0b0706"/>
    <stop offset="1" stop-color="#2b160d"/>
  </linearGradient>
  <mask id="cutouts">
    <rect width="1024" height="1024" fill="#fff"/>
    <path d="${chev}" stroke="#000" stroke-width="54" stroke-linecap="round" stroke-linejoin="round" fill="none"/>
    <path d="${cur}" stroke="#000" stroke-width="50" stroke-linecap="round" fill="none"/>
  </mask>
  <filter id="soft" x="-5%" y="-5%" width="110%" height="110%"><feGaussianBlur stdDeviation="1.6"/></filter>
  <filter id="softer" x="-5%" y="-5%" width="110%" height="110%"><feGaussianBlur stdDeviation="4"/></filter>
  <filter id="haloBlur" x="-60%" y="-60%" width="220%" height="220%"><feGaussianBlur stdDeviation="50"/></filter>
  <filter id="haloTight" x="-40%" y="-40%" width="180%" height="180%"><feGaussianBlur stdDeviation="16"/></filter>
  <filter id="lift" x="-30%" y="-30%" width="160%" height="160%"><feDropShadow dx="0" dy="18" stdDeviation="16" flood-color="#000" flood-opacity="0.6"/></filter>
  <filter id="tileShadow" x="-20%" y="-20%" width="140%" height="140%"><feDropShadow dx="0" dy="12" stdDeviation="14" flood-color="#000" flood-opacity="0.32"/></filter>
  <filter id="glowWide" x="-60%" y="-60%" width="220%" height="220%"><feGaussianBlur stdDeviation="18"/></filter>
  <filter id="glowNear" x="-50%" y="-50%" width="200%" height="200%"><feGaussianBlur stdDeviation="5"/></filter>
</defs>
<g filter="url(#tileShadow)"><path d="${TILE}" fill="#141010"/></g>
<g clip-path="url(#tile)">
  <g filter="url(#softer)" opacity="0.9">${conic(512, 512, 760, TILE_STOPS, 0.7, [0.2, 0.03])}</g>
  <rect width="1024" height="1024" fill="url(#halo)"/>
  <path d="${B}" fill="${EMBER}" filter="url(#haloBlur)"/>
  <path d="${B}" fill="${EMBER_HOT}" opacity="0.7" filter="url(#haloTight)"/>
  <rect width="1024" height="1024" fill="url(#vignette)"/>
  <g filter="url(#lift)"><path d="${B}" fill="#000" mask="url(#cutouts)"/></g>
  <g mask="url(#cutouts)">
    <g clip-path="url(#bshape)">
      <g filter="url(#soft)">${conic(bcx, bcy, 420, BRONZE, 0.35, [0.33, 0.13])}</g>
      <rect x="${x0 - 10}" y="${t - 10}" width="${width + 20}" height="${b - t + 20}" fill="url(#shade)"/>
    </g>
    <path d="${B}" fill="none" stroke="url(#bevel)" stroke-width="6"/>
  </g>
  <path d="${chev}" stroke="url(#recess)" stroke-width="54" stroke-linecap="round" stroke-linejoin="round" fill="none"/>
  <path d="${cur}" stroke="url(#recess)" stroke-width="50" stroke-linecap="round" fill="none"/>
  <g fill="none" stroke-linecap="round" stroke-linejoin="round">
    <g filter="url(#glowWide)" opacity="0.85">
      <path d="${chev}" stroke="#ff4d00" stroke-width="38"/>
      <path d="${cur}" stroke="#ff4d00" stroke-width="36"/>
    </g>
    <g filter="url(#glowNear)">
      <path d="${chev}" stroke="#ff8a2a" stroke-width="20"/>
      <path d="${cur}" stroke="#ff8a2a" stroke-width="20"/>
    </g>
    <path d="${chev}" stroke="#ff8f33" stroke-width="13"/>
    <path d="${cur}" stroke="#ff8f33" stroke-width="13"/>
    <path d="${chev}" stroke="#fff1dc" stroke-width="5"/>
    <path d="${cur}" stroke="#fff1dc" stroke-width="5"/>
  </g>
</g>
<path d="${TILE}" fill="none" stroke="url(#rim)" stroke-width="3"/>
</svg>
`;

writeFileSync(join(here, 'icon.svg'), svg);

const { chromium } = createRequire(import.meta.url)('playwright');
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1024, height: 1024 } });
for (const [size, out] of [
  [1024, join(here, 'icon-1024.png')],
  [64, join(here, '../../assets/app-icon.png')],
]) {
  await page.setViewportSize({ width: size, height: size });
  const sized = svg.replace('width="1024" height="1024"', `width="${size}" height="${size}"`);
  await page.setContent(`<html><body style="margin:0;background:transparent">${sized}</body></html>`);
  await page.locator('svg').screenshot({ path: out, omitBackground: true });
}
await browser.close();
